id = "org.notstandardnotes.theme-dynamic"
npm = "sn-theme-dynamic"
github = "sn-extensions/dynamic-theme"
main = "dist/dist.css"
name = "Dynamic"
layerable = true
content_type = "SN|Theme"
version = "1.0.4"
marketing_url = "https://standardnotes.org/extensions/dynamic"
description = "A smart theme that minimizes the tags and notes panels when they are not in use."
