id = "org.notstandardnotes.theme-solarized-dark"
npm = "sn-theme-solarized-dark"
github = "sn-extensions/solarized-dark-theme"
main = "dist/dist.css"
name = "Solarized Dark"
content_type = "SN|Theme"
version = "1.2.7"
marketing_url = "https://standardnotes.org/extensions/solarized-dark"
thumbnail_url = "https://s3.amazonaws.com/standard-notes/screenshots/models/themes/solarized-dark.jpg"
description = "The perfect theme for any time."

[dock_icon]
type = "circle"
background_color = "#2AA198"
foreground_color = "#ffffff"
border_color = "#2AA198"
